### ISSUE TITLE
Transferring this repo

### ISSUE THREAD

**Issue by teoliphant** [plures/datashape#234]
What are thoughts, around transferring this repo to the Plures organization?

Plures (xnd.io) is a collection of libraries for managing, manipulating, and processing typed containers in many languages. 

Plures depends on datashape and will be supporting it.   Let me know if there are concerns.

**Comment by teoliphant** [comment]
@llllllllll or @dhirschfeld do you have any concerns about transferring this repo to Plures?

**Comment by teoliphant** [comment]
OK.  I transferred this repo to the Plures organization and then forked it into the blaze organization.
Hopefully there aren't any issues. 
Datashape will be maintained by the Plures org as it is the data-description language foundation of plures/ndtypes.

**Comment by dhirschfeld** [comment]
Sorry for the slow response - it's end of financial year here so things are very hectic!

I'm fine with the move, where it lives doesn't concern me too much - my interest in it is pretty much just as a dependency of blaze.

I'm am however curious about the relationship between datashape and ndtypes. My assumption was that ndtypes, having it's own python module, superseded datashape and that datashape was going away (or relegated to merely a dependency of legacy packages such as blaze).

That appears incorrect!? However, I remain unsure of the exact relationship between ndtypes and datashape and where the datashape python package is expected to be used?

**Comment by llllllllll** [comment]
Wouldn't plures want to use libndtypes over datashape because it is written in C and would be easier to port to different languages? The specification for datashape is fairly simple, does everyone need to share the same concrete implementation? Also, should blaze committers be able to commit to datashape? It is a vital dependency.

**Comment by teoliphant** [comment]
OK.  Thanks for the feedback on this issue and for clarifying.  I thought changes were added back to datashape as ndtypes matured.   This is not true.

As a result, datashape and ndtypes are different projects with ndtypes having been "inspired-by" datashape.  Thus, transferring the repo is not appropriate as datashape remains an important dependency of blaze. 

I would like to see datashape updated to use ndtypes, but don't have resources for that at the moment.  If anyone is looking for an interesting project to work on, this might be one.

Thanks again and apologies for my error.
